# Generated by Django 3.0.7 on 2020-06-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200613_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
