version: '3.7'

services:
    web:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        env_file:
            - ./.env.dev
        ports:
            - 8000:8000

    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=portfolio
            - POSTGRES_PASSWORD=portfolio
            - POSTGRES_DB=portfolio_dev
      
volumes:
    postgres_data:

networks:
    default:
        external:
            name: nginx-proxy
