version: '3.7'

services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000 --log-file=- --error-log=-
        ports:
            - 8000:8000
        volumes:
            - static_volume:/home/app/portfolio/staticfiles
        env_file:
            - ./.env.prod

    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
      
volumes:
    postgres_data:
    static_volume:

networks:
    default:
        external:
            name: nginx-proxy
